name: Build and Publish s&box Egg Image

on:
  push:
    branches: [ "main" ]
    paths:
      - 'images/sbox/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: mydrissjlv/sbox-darkrp.xyz-server-egg

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: ./images/sbox
          file: ./images/sbox/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest